services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      # This 'anonymous volume' tells Docker:
      # "Do NOT use the .venv from my computer. Use the one in the image."
      - /app/.venv
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - WTF_CSRF_ENABLED=false
      - SECRET_KEY=7b117610f157300f7245315bbfbb713fc95d14dedd00b2e7a1514557ed14b17d
    # We call python -m flask directly
    command: python -m flask run --host=0.0.0.0 --port=5000